[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SimulationSupport"
version = "0.2.0"
description = "Support for SpEC and SpECTRE simulations"
readme = "README.md"
license = {file = "LICENSE"}
authors = [{name = "SXS collaboration"}]
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "torch",
    "gpytorch",
    "pandas",
    "sxs",
    "varpro @ git+https://github.com/sxs-collaboration/varpro.git@978106eaf3d7a6a7f0c5f167726d8e0fc59fc95d",
]

[project.optional-dependencies]
dev = [
    "black",
    "isort",
    "pytest",
    "pytest-github-actions-annotate-failures",
]
docs = [
    "sphinx>=7.2",
    "furo>=2024.7.18",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
target-version = ["py39"]
line-length = 80
preview = true
enable-unstable-feature = ["string_processing"]

[tool.isort]
profile = "black"
line_length = 80

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra"
python_files = ["Test_*.py", "test_*.py"]
